apiVersion: ENC[AES256_GCM,data:AuY=,iv:IuOsE4/lm3ySaAQ2AtfChHR/BYa1t/h+zqgaFzAEx6E=,tag:IrWB3lqD3701YGOJQH4hjw==,type:str]
kind: ENC[AES256_GCM,data:78hh/lEn,iv:yc9auadTaYxeyKuToHF0mwO5F5XwY57K4ySmMv/ObJg=,tag:uIub8xjIhvbn4rjxUX01tA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:n3/f0plnT6Udf4nKGj+K0p9mNuo2xu+j,iv:liEN3pqb4aLTnQ8KfD7S9RHeI1JULrofXz1q1VeCMmQ=,tag:GgTc6Ho5XuELA9HYwAgxZg==,type:str]
    namespace: ENC[AES256_GCM,data:8nGHnrS81lqG/Hvl,iv:Wz8cmaNetIRSLh+00GJ/IFuk9M6vxq7haSVD6py1RZE=,tag:43Vyx3C/c17CfcJ7OYj7bA==,type:str]
stringData:
    client-secret: ENC[AES256_GCM,data:kXADChhEGFKPeamdQYgvFgulE/FDMBuKXKAC3TwVk3kp1G100Dt0uwfXACTkewbY,iv:LCT7ckAfVwy4kceuRD/AbwWDAm/Ab5M0uPXlDwpI9gA=,tag:dzraO4R/euLaNN+fHYJcqQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:mhkOm0+lLu2v5XCYLD6d0bEn3sYL/YobDeJN6p2tSvLLQua7evMkOstTfw==,iv:+iw8dkgZzgrmh1cvzp1bvH/Xnwr+V+8CISvku2rmMMY=,tag:D3soYpSd4EDhCxhdDSXCVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QzlHOVRuWUJFU2VZaElC
            UzIzRHlZVDJydWx4dHhvLy95TlBtdks2RHlnClpmQUFLU3FuU1oybEh1YzZsT3U2
            SVFRZllVM2x0VE03TEU5ZXQ4U2o2WTQKLS0tIDM3VStsbC9XT0hMUWdDRWhLUVlM
            SURjWnVNUURlT0dOVVBnckt6bUcwV0EKRNTuhUdcWQdldP88nv/a92z87CvxYMeM
            jaRcUKfPkIreBRnlYVHhO3lZsNBHkME5IELMLSIsKUWKL5NkMlRx3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-18T11:26:52Z"
    mac: ENC[AES256_GCM,data:qlUx5orR1Jrpx9eLHjX0bx1e/au137OOSLJ12bJ2a+fn9sxwv+KaKwys0ibjBZS806EjOsJDq0SEPKVO5UHDu5CA04RMLUHjP5DWN2NBodKFHZxkIecjwx3hjBGcrI2rW8Aa4NQH+v2Zj6zjsy7zyguSqtbqJmXjer8EIO7jFng=,iv:6fmyBdPUg5JWw5EpkrGjV5kmFVcIoxcbH1CA6gz4TBM=,tag:QS/V5dYTaLavTxLHUc0aLw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
