app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: quay.io/oauth2-proxy/oauth2-proxy
            tag: "v7.7.1"
          args:
            - --provider=oidc
            - --oidc-issuer-url=https://auth.lab.tanku.eu/oauth2/openid/oauth2-proxy
            - --client-id=oauth2-proxy
            - --redirect-url=https://oauth2-proxy.lab.tanku.eu/oauth2/callback
            - --upstream=static://202
            - --http-address=0.0.0.0:4180
            - --email-domain=*
            - --scope=openid profile email groups
            - --cookie-secure=true
            - --cookie-domain=.lab.tanku.eu
            - --whitelist-domain=.lab.tanku.eu
            - --cookie-samesite=lax
            - --cookie-name=_oauth2_proxy
            - --skip-provider-button=true
            - --pass-access-token=false
            - --set-xauthrequest=true
            - --ssl-insecure-skip-verify=true
            - --reverse-proxy=true
            - --real-client-ip-header=X-Forwarded-For
          env:
            OAUTH2_PROXY_CLIENT_SECRET:
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-credentials
                  key: client-secret
            OAUTH2_PROXY_COOKIE_SECRET:
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-credentials
                  key: cookie-secret
      pod:
        hostAliases:
          - ip: "10.97.114.105"
            hostnames:
              - auth.lab.tanku.eu

  service:
    main:
      ports:
        http:
          port: 4180

  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host oauth2-proxy.lab.tanku.eu
          paths:
            - path: /oauth2
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: oauth2-proxy-tls
          hosts:
            - *host
