apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vaultwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.lab.tanku.eu/api
      identityURL: https://vault.lab.tanku.eu/identity
      auth:
        secretRef:
          credentials:
            name: vaultwarden-credentials
            namespace: external-secrets
            key: clientSecret
      organizationID: "c689a7bb-22c7-40c0-87af-309a7f2ba168"
      projectID: "c689a7bb-22c7-40c0-87af-309a7f2ba168"
