apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vaultwarden
spec:
  provider:
    bitwarden:
      apiURL: https://vault.lab.tanku.eu/api
      identityURL: https://vault.lab.tanku.eu/identity
      auth:
        secretRef:
          credentials:
            name: vaultwarden-credentials
            namespace: external-secrets
            key: clientSecret
      organizationID: "50a5a9cb-d4a1-43fb-ab72-b5329237e608"
