apiVersion: ENC[AES256_GCM,data:4Zc=,iv:R44gOMVmaQaa5Joa9IOkIvuh2t6oyI4jDywomWRsG2A=,tag:H3OvWtOVrUUwLT8o7ksoUA==,type:str]
kind: ENC[AES256_GCM,data:SKVStLYO,iv:pN1c97fRGmEBPpe6YAvJy99yp4jpmMy2UadhFYhTBhw=,tag:cgbDFn4318/d252hjL9PGg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:J4dYCelvfd8aCp82mX5wvlkZQ3ymwtU=,iv:PB04pVolsqkbEX2UHscFnAtNTSkiPZ/tDOY8oqzRVKo=,tag:TtO8KrdrspHEuSgOypkM2A==,type:str]
    namespace: ENC[AES256_GCM,data:1I6UrV8xyXTSzzeirrCE1A==,iv:JJ9ajW0El/CjUc8JWHVqGfbJJHgd7LkQDd59rtQNrQs=,tag:J8JjFUff/HifJoXMv2I0dw==,type:str]
type: ENC[AES256_GCM,data:an0byc5X,iv:U3ubF13XLJdrqv8DscnFbWXmLVNLfnxqyavCrYkMvjg=,tag:8Ju+PepbyWTspa/g1//LsA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:SQl2AQmXtyt/90CXaEZhBK7ruPalpYEH4FhDHsZynbHTluw2BtAzx+k=,iv:GjoHFai4bkRo8WNRuzUWIJfV5Jr8TJIHf638MKNEiIA=,tag:m9+++dbW65+zy3jjYQwgtA==,type:str]
    clientSecret: ENC[AES256_GCM,data:QNUxLYR6XjDg1o0uuuZejpTgA+5knyGFRjlmLRMP,iv:MC0vHEKgI6NcdmlWOp+wMNlFaq47CPAulnzH0Divhqs=,tag:kjA2Vc5axvFFLWSbVk44vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRVF2UFd3M2l0clI1Q0JK
            VWc3aW4zQ01ZYTdlaGdnNUt2bnpVYzVrNGhNCmV5dTUxVklGNkkrOTI4cWRoMFcz
            VUV4VUh2SHhMNEN5Yy9zakFSZU5lV00KLS0tIEh2TWE0L2tFYVRTY0dTajhWM1Er
            RytXUEpYZURmZTQwVnArWW1mdHVNeFUKvMih1DS0YKT4i4GznV3uLLgaT4/3eAm+
            ncRtNqcSKDo/LevTfVq/2iK+mVW2VZQGxoeiTvJmZAyycLDJ906M4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-14T19:47:58Z"
    mac: ENC[AES256_GCM,data:dIq4EZyAOO8IUohUsLKKjB4N2yNIVH1+t1+j/oYL5dpaEZYGN/V/kwv4ETGoQ/MRaSBiIdEbNHy/YZvb6KxPsMTBfagQ8b0pFJewQVMCjF0hzkZp2iRe/nHHEpLKQEw5nFLgOsRmJlyV3JJeM7p/JhvCVxAXTbFpuA8+i5FLGB8=,iv:wDSCZMIDmrzk9qdM4+0qV1wbouEUGrGlLTbz4sUZJ6w=,tag:VZZnCUusm0sn37k+eSVUgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
