apiVersion: ENC[AES256_GCM,data:TZo=,iv:F44/vpy4a7P4WP8C/e44oKR2OPF0fPu2PBBeHHhLZUA=,tag:gDQ+IKXaRac/geJ8fAXpsw==,type:str]
kind: ENC[AES256_GCM,data:nwPVghi8,iv:eCc2aMNEEIjtfaleGBUU6r43IlfaN5g6aKfouZhT1jE=,tag:V/ozspAzVzan6hCj8eSNxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ga4UaRTsbJ5YqZrYGcIi8s7gBkCJ6w==,iv:Bu2wQhUqhebVaCdudWO7D6IIdQe5hkGtlTE/gpuFwMQ=,tag:kCNFKYNVX+r13J2lWy4m4g==,type:str]
    namespace: ENC[AES256_GCM,data:To4/p0O+gH+Efg==,iv:ibGmG35DVlr3NXxxakJeeX/y6+Nuh+A4DA3pVukSz4A=,tag:IjpTDP1h5Iui86gFoqN32A==,type:str]
type: ENC[AES256_GCM,data:sQTwQhB/,iv:cSMqCLBHio9BsHIfyx2SyZoLnsGmeRrTyIk2pOLTrQw=,tag:C3QEykUPol20WrqDDRp6Eg==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:dXOOfgkMHMUVxTf39yb5LpMJw201QadpR5gbDT3slzYb7GO10YGxl+kX1P8=,iv:avy2rsrtHmJ8Sg4likUyTWJmiqmX7Wg+aPTJ/CNzLDU=,tag:AfVm8kdNvaoSk4ek9Yk4Mw==,type:str]
    CSRF_SECRET: ENC[AES256_GCM,data:34pG5dN5UpNtKQe9IMHH2rtIbi4wpr8vIS77QeacsnGarG2O4MsoCvX8cTM=,iv:NP6L2KFFLgQohr6I5egywW7SgHCg8n/F527gvvgldY0=,tag:+wvwgJqUX/qIt2YmF7GgBA==,type:str]
    API_KEY_HASH_PEPPER: ENC[AES256_GCM,data:eMcVB4xClHMaSCkHgzCWDru0StgD2jguA4dHws1TRHTp8v0HQO5iP7DDFjQ=,iv:M6Uj2AVUh5UowF5kCLrU61bDf1pEHYW0sBE4nTckYbo=,tag:NDZ9BApg80VpTkMLQOHmUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOVl4VU1uYkd2cnNDOGdh
            ZUluQThrQnBVTzZTcUhWc1Z1WXE2dDVRUEFjCkV1MGRmN0VSbkJ6Z1pvN3JRUURT
            M1NWdG5zN2JBTHNZSzl3aVJRN09uZ3cKLS0tIHNOQlFlWlBzdnQ1aGpXLzZtdWFX
            c0lhZDUwZGozTldmMkZsZUN5TzlLU2sK5ZJttZsMqG4dTdcFC/+pdt6+DABmjQna
            7BiXB/mhjnr0vI8FsWbGoq/Wy2BMK4pcWuwTQXtas+mFJEtE3EsCnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-18T19:21:33Z"
    mac: ENC[AES256_GCM,data:xY/uzPTC2bIP0G0+0urtPM91+GriUO61krs5m5LNjKD2iTIdSiGewjJFygWZFbI8X0UXN3V1wxaWlG9di7H7StRcqdY7wBD0kOQAYairF+zEKkqTVdqPYO8m8l2ydx73qxpbp35xoQtTy+XMuh2J/Qv86PsI96V87VCjhmnm++s=,iv:PwQzy33fRr7PsOq0nHfJm9c5q7WogjNcolEWha+903U=,tag:w7UH1zA1/Vsp4ho3weQbvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
