app-template:
  controllers:
    main:
      containers:
        backend:
          image:
            repository: docker.io/zimengxiong/excalidash-backend
            tag: latest
          envFrom:
            - secretRef:
                name: excalidash-config
          ports:
            - containerPort: 8000
              protocol: TCP
        main:
          image:
            repository: docker.io/zimengxiong/excalidash-frontend
            tag: latest
          env:
            BACKEND_URL: http://localhost:8000

  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host draw.lab.tanku.eu
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: excalidraw-tls
          hosts:
            - *host

  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        main:
          backend:
            - path: /app/prisma
