apiVersion: ENC[AES256_GCM,data:WlY=,iv:2P4oiPnugLUmAz19ScCKCWYGojTyrqDdokx77HcDZng=,tag:VQwAf7L+hpiRz2AMc5fi4Q==,type:str]
kind: ENC[AES256_GCM,data:ag7XO8tF,iv:qBl2j5NBu+hGAyx32twGOx6GpnbSv1aqhMwwZGq34hU=,tag:I2v6S+PBOPInL29GLekBTA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s+Cby+DAUbrjKJfy1c9wmCQ=,iv:vhqNJshdT3HUbF0R0kkGow3NjKY3tapMl5qKJC7CN3E=,tag:sPUlsWC1MkL7c5RjZMbb6g==,type:str]
    namespace: ENC[AES256_GCM,data:JV8v+9+/o8O/2w==,iv:cqAkjx/409PeeeKTkcqbVG0jcksU8+HxqDdA80pwQnM=,tag:tyM9vZXZFLhcc0pi1SstLA==,type:str]
type: ENC[AES256_GCM,data:BMKFzCec,iv:fjFbgj0xcUSpa5NkbS0dHTem/Z+rGb0n16NMpbe3RiQ=,tag:sRLp2bU4qZ+sCW+dBIe2/g==,type:str]
stringData:
    jwt-secret: ENC[AES256_GCM,data:dK6XvCgbBkjaOk9d93G97i7jmP4p2TYMHOlIJOf+O4jg39w11qjLvCSkqMhYajA2yOcrCpNOkCe98Sv2exf7hw==,iv:KRD1aMgB9U1iVH/3ESDUFzmTYFI663Lj++tK/Hmd2Uc=,tag:o7x7TcclgZUKWEUFTk1Q6w==,type:str]
    db-password: ENC[AES256_GCM,data:JIjMXshOBtPMm/vQboXE8zufwKn3vg92wcyXgY6Z6g==,iv:bEp6atLO+iYSMkycwErdXgZ+FKoZADPMmdQW+Vm4Xvg=,tag:h/qtLd/Gmxvb8Vj56HF7aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVG52SG5RZnp2a2VtUHZL
            RGNUN1hSNWQyUDBnYnBGT01lbWRaNzJUK1VvCjA1eWFiRFVtVFBrU3psUWRVUHdD
            aEE4dURsVXdtRzU1VHE3RTRkSGJJS2cKLS0tIEVKU2dZUm00TjB3Z3laMDNWSEtZ
            bGZtN015NVp1RHE2ZEhTY1BreTcxc1kKs033OTvRVM/ilQ3ZAxJb2FcSrhDEei5K
            2ereDNbetddJ4FstUJyb3Gp1MtjJ2sD/D04uX5P4KBTIgk5qc0Z3rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-17T19:45:57Z"
    mac: ENC[AES256_GCM,data:sPzHJYM7ktU6mOMESWL7xrTCkOMVCE4EKZCG0mXRD63gGS2bz+e6ooGScUkkfJRaxs6ISI2BN0axUGmylw3D4grbuSMMaoidxX4PVnNhQ0KeMCgzXtqBw/ztVDAOomDhXCsRgPwrmff9Qv2d7f0GXM36FfDq4wI21PMcAiuksgg=,iv:2DVpk+UQP+50PkEEYdrzlUw9e+eTBe1XLa7IpERnGuk=,tag:aJbGdeALtKe8uEPkFGMm0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
