app-template:
  controllers:
    main:
      type: statefulset
      containers:
        main:
          image:
            repository: docker.io/onlyoffice/documentserver
            tag: "8.2"
          env:
            DB_TYPE: postgres
            DB_HOST: postgres.postgres.svc.lab.tanku.eu
            DB_PORT: "5432"
            DB_NAME: onlyoffice
            DB_USER: onlyoffice
            DB_PWD:
              valueFrom:
                secretKeyRef:
                  name: onlyoffice-secret
                  key: db-password
            REDIS_SERVER_HOST: redis.redis.svc.lab.tanku.eu
            REDIS_SERVER_PORT: "6379"
            JWT_ENABLED: "true"
            JWT_SECRET:
              valueFrom:
                secretKeyRef:
                  name: onlyoffice-secret
                  key: jwt-secret
            JWT_HEADER: Authorization
            JWT_IN_BODY: "true"
      statefulset:
        volumeClaimTemplates:
          - name: data
            size: 10Gi
            globalMounts:
              - path: /var/www/onlyoffice/Data
            accessMode: ReadWriteOnce

  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      hosts:
        - host: &host office.lab.tanku.eu
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: onlyoffice-tls
          hosts:
            - *host
