apiVersion: ENC[AES256_GCM,data:2eo=,iv:iNj/SVNE0WZRKRmNJBv53dc7b/ti4gGYucyqF2XxhQo=,tag:ZTcCZktnp1FVr/jRkSY9WQ==,type:str]
kind: ENC[AES256_GCM,data:K5vPGkKw,iv:7FkS/LkFsrbISjJH2vdSlQknT5RskwsRjuCHMC3LGcc=,tag:pkYoKzuUOzvmpS+lJt7iBg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dIXIlqrW4SEdldxFJLpXQoSmpKRA,iv:3bb0uBciPDTLyTW/d1tZq30bgVz3Y5kVcw0s+4htrWc=,tag:wkYfv2MIF2CWFSr0MrUTdA==,type:str]
    namespace: ENC[AES256_GCM,data:wRWL24qeAQ02,iv:FI5Z0E1HhX5i6L3R392qGyfNgIZpjxXvTIhAIrzXX9U=,tag:t7H8NA9PDvbffna9FIeOMg==,type:str]
type: ENC[AES256_GCM,data:iiBmXMZm,iv:1XgOjQmuCzhuUE7uhT+MgaYxmYm7IrIh4gPWhC9sC4U=,tag:7AapRntHiqzbd0I7bQ2mMg==,type:str]
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Sn6gwWdWLSqnDOxZJCWUnVPM60udfhVSeLBMGx4SmwQw9wF3QtipSyUPMpLCnhbVsSXBn/gF+/1j4/YcA+5hVQ==,iv:sSIqj0yLhFYRnm/suoi0vMlM7cN7JmSzIkhJDcIhqCQ=,tag:BdxG/mEyEe/M1/clMi8x6w==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:UML1e6RfUFxtWzkT4n+X+ayshkVYdLh+crCT5TCY0GQ=,iv:IcBFPeSzD2cvfoqFGNmTb7/ehvCSD5fCs7GkXZskZgE=,tag:jCqz0MG2a40o9DS3T3jpRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVC92TkM1UzJlMDlkR0Rj
            OU9sLzFOenRaR2U2Tmt2R1NVcWRhR3REWlNvCkM4NTlEcmpCd01OMmlXQmpCNTJK
            TUFUUUNmbnVoYTdXTHowRlprUmphd1EKLS0tIE0wNHZwajRKNVdEU3kwSVZjTTNF
            ZjVaYjBIRlhzY28yVUlYUmJIOThKS2sKkwCkmayzPP7Emd5O7K3JxQcGuHjfKjh3
            N7Bbf1ySZQyn4rxYi++7TqbQ3KTN0HKs4El5NG6YVmWCCUgEqpLCaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-17T21:18:24Z"
    mac: ENC[AES256_GCM,data:HRtqIK5s0A2ST2chxOxS4/RzBAZYrRCzPinAEqIIYOOHqUH/GiNy6XKiYyDzPz5oxjtYVN1LOgZSXcK2qNmABRtOoBtF8m6k2CORq7RYdVWAuI8OgwRwsRsD9sC7sXwMsAfsDALMpYiEz2WZdQ918JGiI4DcE0fd2VNTsVO4r68=,iv:1ZX9V3k+lSW4TEPIq9HSimej7nJDRQvdlPT1tB0akNs=,tag:xbfPoUAYYkrNP/tQ9U6hGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
