apiVersion: ENC[AES256_GCM,data:Mnc=,iv:x6lLqDFsZ2ir1hsBZ3SpbLuzqbxMy41YpgmXJ5Fftz8=,tag:BEfEsTtPutNdDq1w54dE0A==,type:str]
kind: ENC[AES256_GCM,data:gFvdtpAL,iv:vpzL73qp1+1VUDQu4hxVt0PqiRNwCSiHOChHLUylrL8=,tag:FvrymkYhASeGT+sQztdumQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cKEA72zJpMJyf4yl/lEQCYufbMzc,iv:SkPRlJxKBO6SjIEXNY8+1KBt4B+7OkbPM5jdoMDEpqA=,tag:LEJOFtODEt/NRtDbzkIGZw==,type:str]
    namespace: ENC[AES256_GCM,data:ja+FSepkYtVu,iv:OAMMimtHW0oPeVKRU3wIkniAGkrBEsEebur0BNAtzEo=,tag:X0zR6n/8plxsiW2JnEPlTQ==,type:str]
type: ENC[AES256_GCM,data:yGohF7oE,iv:AXANdSfbzrl0n+o6pOzzbbh51KMvEENBmfpqh52b21w=,tag:wKNkNtfsgwOR/GfZUus1xQ==,type:str]
stringData:
    nextcloud-password: ENC[AES256_GCM,data:2aKO+JHW5Vi9w3s4qedDgyDfkyZJr66deJzUnVag,iv:bZG1ZV+bFhWDfM1ZkxtaMF+rb5aPd5YCcYFxe0VlVu4=,tag:XyQd9lTRvkosX6ICFizJIw==,type:str]
    db-password: ENC[AES256_GCM,data:Uvu3vyDB1F7loNZDFa3rPFz48aBwu/liItXBdg9uiw==,iv:k4+sU2KdiPzH2Tt4nT1DKNifHAtUk5KsmE3z8YqGbV4=,tag:NOlA0iE6XhYBkFQRqm3AjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVnVNS1pNWEtpZWMrcU81
            T1dpdk1qYktuUWNlV2lOODI1YVduOWxnc0FJCkJHa0hQSVRIV01GWnhubXMra3lV
            ak9jZlN4Qy9YaXhldkhpZnl6UHJDcVUKLS0tIE5HaHNFbG5kN3ZqZWM1eEtEeUZ0
            S1FnZlozT2JHMjE0R095akk2RytaZWMK7FpqLQj3N65p8ZbYuAVd+d/AXbfO2Ty3
            DYERBWn/Y1vJBdJCd/KEbNFtr7/JOrxhWifc3zVJLHAo43wkhDuh3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-17T13:27:27Z"
    mac: ENC[AES256_GCM,data:AUQhWK2i8kg0pbANkIvoOD22eb8o/4z+0b8O7Wv41Y25LI9EmS869dSktn/48YfOrlM2FuNiRhIvXOCQCfY8NYWEM/ROJn7khLZnFLnIled+l8nrhZi81VW3v4voluBCf7+apR7ehPKRLyTjS4IArJwXh2z0ihJdZyRn5YwSs78=,iv:Qt6PD/tBgMKeW+3UUzz+1IAEf+Dg6G3SzsPtyFEB3cQ=,tag:hQ9YW7LdOVOVXj895ASrdA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
