apiVersion: ENC[AES256_GCM,data:JL4=,iv:uxDJFvJG7CGWrmSYkC3pwmfv/CiJgrfMHBfoHIRKKvI=,tag:N6mHqiXyOpkFFlw2+LEIbA==,type:str]
kind: ENC[AES256_GCM,data:VWEx8LE4,iv:WjgX27v9D5PSvQZZS//EI7ItzuMeHoSn54py+90VGvU=,tag:NSW12TyJYS234SsF0CYsPw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uEgO4qCidgW8Elur+23iDLyfGsxa,iv:6w3b+6ngRNfT/ZotBPUUX/cO5fUOA2EU5ndlKtj8FiU=,tag:ZjRSy0qBYdM+32aODe9fdg==,type:str]
    namespace: ENC[AES256_GCM,data:ahx0fUhUKP89,iv:QHwqGMu0v464Lho/JVO6I6hThSkQjN4nfi1js50xdok=,tag:0pb15l5GcoJCRGrjl2IrAA==,type:str]
type: ENC[AES256_GCM,data:cBlJplik,iv:Lu91DPpVRoxxHqyuyleCUq2vFp/dspIyhl/FMUxiC5g=,tag:Bl3bPM0IvaSp5Y9Yk4cg7Q==,type:str]
stringData:
    nextcloud-password: ENC[AES256_GCM,data:9p3qemzXkoG+4mxFn4q9vstcwH6teGzoeFKy6YXo,iv:QG9ICjp+nIEVHrmFLxAlC3M/6yrTXlHv7W03nZ7dra4=,tag:iXOsLPufKqTdsFk5l/83ZQ==,type:str]
    nextcloud-username: ENC[AES256_GCM,data:FfMMuf0=,iv:QjTR3qmJqbIANRTkxuWwKOvD0Ry6OLmE2UzHpeONpKA=,tag:kHY3sXB42K+Q5AA+jSxhMQ==,type:str]
    db-password: ENC[AES256_GCM,data:Bnar3rElIGocdLVxrfFTUpwSKydLtRcDg58GZB3x2A==,iv:WnHTm7uQUFtGM4nan5MYvGj47Oni6IZsrL6Vx5ToddI=,tag:5hvjieTowvGFtcUnHmesCQ==,type:str]
    db-username: ENC[AES256_GCM,data:wuqU1PuaPw1o,iv:36p54QeKHGPLJct9Fi9xZCjUFNmHOXtunTo5kGuN2aY=,tag:Zho31ZONEcKJmlUkvltxIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQngrWTNFNXljanVhZW8v
            dnhCWDRBWlRuTVR5SnJDZWtPWldkT1huUDNJCjk0RlY3K3pYbDRGYUUvYm9TMW5E
            TEdDdW1CWGtNMUFKWWgzUmxOb1J4d3cKLS0tIFJqcm9BSFd3c1RGSkNvL3dBaW5k
            L2dPNW9rL3lSV1Vtd3ZaM01FUFNTQUEKvzvVnX9rQ6hqGP6DPxSZANLiY8jtR7Gx
            ipftvyg5dp1u4Mwh1CMs3hvD31+EhPms1cQ9L4+LWfNnNtZf0LD7Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-17T14:18:07Z"
    mac: ENC[AES256_GCM,data:5Qz2F1uwSfLC8aYc5qomu7r8ZVhNYhX1B7/LKxWjY6Ff+0LELAb6r7Q3L8HLp58GqWngYAmUrmj0v5kZO/aQkmGfkprV8mOiI7PJXI1IuMI7SXfBdH8nqnfbJLcMiSpuwccOF/ga10PRf091LKLvBxkwyDhMVcET2V0Kb3pspPg=,iv:N5MiWqnxzAjdgHK5BQeoQdxvOUZeiB/sxA5GbS9vq+g=,tag:EFyqSMT17neKqKz+yxT83Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
