apiVersion: ENC[AES256_GCM,data:rqw=,iv:AHrvFf1vHcrxz/iWm9iIJQP0Jjz1z58fT+HsxR/SDPk=,tag:lIxTXCGplxTfhYkNwteD5w==,type:str]
kind: ENC[AES256_GCM,data:WYIhBsil,iv:gbvOS+XgSa/kYyttQCykL4bYngCuFhP8ADS7gWJ2zhc=,tag:O10XTUx4pLwWZZFQaHCVOw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:f6siJzDKexpjhSJvolX3v1UHj1Iw,iv:NqyVG3jc22oamTIOxWhaAdyf7DzIWnm6Oyl8Qjl874w=,tag:JrD4+yHiuf70resbKkId0g==,type:str]
    namespace: ENC[AES256_GCM,data:2bmI1KZS1c+S,iv:B4SEn+856BOhVb9qj0jIdVMvDLecxFJBbR3Nhz/vkkI=,tag:WZ0H4VdOPLQYdi/ZK8GxyQ==,type:str]
type: ENC[AES256_GCM,data:gyWdX0qX,iv:0xcuCqAlGfzuk/+2H+5bCJY6O6VJm7BWlXjh4hbnXHY=,tag:1ZPCMfbzQCx5fayQac/Amg==,type:str]
stringData:
    nextcloud-password: ENC[AES256_GCM,data:vASfcZp2/RbsJFQKkZ/5sBX4TuAPAh/O6SRLbxY4,iv:NQF/Il3Q/l2T7udtegnLSiawdQcJZiyNM0V1S/XLiKQ=,tag:xr2BhuOLhHMT3aMQWk/8UA==,type:str]
    db-password: ENC[AES256_GCM,data:X7qSF0nvbbTyvLBYAe32+qQ8lHCsSwEL0CT7CzrKRA==,iv:OX0fZMX/T+BN11dUfr2SySSXw6esHjsCwjsMEtl3eoA=,tag:KzbPBnxZXd7qxGV/bVvfDg==,type:str]
    db-username: ENC[AES256_GCM,data:YF1twSkwoz3B,iv:06IN7icT/0yES+0Z1xaAb8EhAmM0VeUU/PLxJGKkI+8=,tag:S31YRcVVoTEsgqXP2V7kXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUGt6M3M2SE9LY0kzb2JQ
            QUVQMUV1NUg5UmlnSTl3Uy9vbXQwODZWK0h3CmlMckRMOFQ2WU4zZW9YN2NQR3lT
            MVpuUVVSczZ2Lyt2eWRUS1RER1ZubWsKLS0tIEhBRFlwc2ZnVEQ2TkM5bUczcWRG
            RTIrS2VjMHl4TlkrTFB2ajllUk9ON2sKXhT9KsUM3oylF6bMmB2lqHHonWXOPyCA
            0KnLz3Rtvk6ayqE1Lo+ZobmatXThr6XTkBbApV6S4tCLl1At/T/kbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-17T13:49:05Z"
    mac: ENC[AES256_GCM,data:fyoa6Ky1xYckSQsoDGLsH5+NP+DrsIgYwZ0B8PCaFbRQRzD+DplJ4gaRonsYpLFZq3XYCLHoMouns8n2+rPPx4dxOLmug03DZecX6gUSK1l2H6xxhBXbGF1HZYjrAJuS/9CvM+2kKsd34BVDolvkrTdSpQ2tYHhdRYc40wks98k=,iv:UgcqlUwsL/1ZidGD2UgSLmmoCApPfqIyBhKEZU8dHJ0=,tag:KfQwbbWJpmiSckCIJotDBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
