nextcloud:
  image:
    repository: docker.io/nextcloud
    tag: "30"

  nextcloud:
    host: cloud.lab.tanku.eu
    existingSecret:
      enabled: true
      secretName: nextcloud-credentials
      passwordKey: nextcloud-password
      usernameKey: nextcloud-username
    defaultConfigs:
      redis.config.php: false
    configs:
      custom.config.php: |-
        <?php
        $CONFIG = array(
          'memcache.local' => '\OC\Memcache\APCu',
          'memcache.distributed' => '\OC\Memcache\Redis',
          'memcache.locking' => '\OC\Memcache\Redis',
          'redis' => array(
            'host' => 'redis.redis.svc.lab.tanku.eu',
            'port' => 6379,
          ),
          'overwriteprotocol' => 'https',
          'overwritehost' => 'cloud.lab.tanku.eu',
          'trusted_proxies' => array('10.0.0.0/8', '10.244.0.0/16'),
          'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR', 'HTTP_X_REAL_IP'),
          'allow_local_remote_servers' => true,
          'logout_url' => 'https://auth.lab.tanku.eu/application/o/nextcloud/end-session/',
          'cors.allowed-domains' => array('https://office.lab.tanku.eu', 'https://cloud.lab.tanku.eu'),
          'trusted_domains' => array('localhost', 'cloud.lab.tanku.eu', 'office.lab.tanku.eu'),
        );

  startupProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 30

  internalDatabase:
    enabled: false

  externalDatabase:
    enabled: true
    type: postgresql
    host: postgres.postgres.svc.lab.tanku.eu
    user: nextcloud
    existingSecret:
      enabled: true
      secretName: nextcloud-credentials
      passwordKey: db-password
      usernameKey: db-username
    database: nextcloud

  redis:
    enabled: false

  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: authentik-forwardauth-authentik@kubernetescrd
    hosts:
      - host: &host cloud.lab.tanku.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: nextcloud-tls
        hosts:
          - *host

  cronjob:
    enabled: true

  persistence:
    enabled: true
    size: 50Gi
    accessMode: ReadWriteOnce
