nextcloud:
  image:
    repository: docker.io/nextcloud
    tag: "30"

  nextcloud:
    host: cloud.lab.tanku.eu
    existingSecret:
      enabled: true
      secretName: nextcloud-credentials
      passwordKey: nextcloud-password
      usernameKey: nextcloud-username
    defaultConfigs:
      redis.config.php: false

  startupProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 30

  internalDatabase:
    enabled: false

  externalDatabase:
    enabled: true
    type: postgresql
    host: postgres.postgres.svc.lab.tanku.eu
    user: nextcloud
    existingSecret:
      enabled: true
      secretName: nextcloud-credentials
      passwordKey: db-password
      usernameKey: db-username
    database: nextcloud

  redis:
    enabled: false

  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host cloud.lab.tanku.eu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: nextcloud-tls
        hosts:
          - *host

  persistence:
    enabled: true
    size: 50Gi
    accessMode: ReadWriteOnce

  hostAliases:
    - ip: "192.168.178.224"
      hostnames:
        - "auth.lab.tanku.eu"
        - "cloud.lab.tanku.eu"
