apiVersion: ENC[AES256_GCM,data:wRE=,iv:mpbMTHtTSnpRno84n4N951zFCOJE4zs2IqpbUSE1AFw=,tag:15HmgQ/BF/xTOj/5DBKp5w==,type:str]
kind: ENC[AES256_GCM,data:IdQZ0Jq/,iv:ivdsLmAFDR+WlsEWs32hKaSVQGlKhfL6OMdLQciXA54=,tag:8/3pnhaPBg2q3gLwdnmeXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wNlM9AojyA9u72P8MK0kc1BE,iv:aWE1ds5+bDbndDTkwi9T/22uipPiiR2x16FmMKe5p/g=,tag:uWCJmczFdbZaCD4ihaviTQ==,type:str]
    namespace: ENC[AES256_GCM,data:Xta0DIb5,iv:w4AA2Bivk5+UNhc9G5MqPYSlyaUe+2QDVeLikAPn+GM=,tag:nptE9Lrbq3lwYIAaRIsUbg==,type:str]
type: ENC[AES256_GCM,data:tvGxplpF,iv:8UFD1SqDaZdjod/6xSO19Jyso2UXU+BDHhQO6vvdweQ=,tag:hmOGN9vdL+ivL2ZqU7nVWA==,type:str]
stringData:
    db-password: ENC[AES256_GCM,data:Y5e1qFml5vtWZkku3VTF2ZeP2UBD10P5ElXZHFYCLjg=,iv:VrnY2yREgD26QBo99Nl/EpYOJOKbLZvmP5KSjjci+7c=,tag:BrL2pmQDYAZEG5MVJRgKFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcmV2MUVPRkpqODQ2YVFm
            eFEzeUtRRWF5cm5QdEFPYzF4bzl2cTNsampNCkZxR3BjclB1ZjBXTjFodk1POTI2
            eENRUkxHbUh5UWplM3BhcGVLZ3YwNVUKLS0tIFA3bDVkbzMyT0dKeDZoRDRDRnV1
            azVZck95NkRyNDhhS2pvbnYwZlFMcVkK9VdsLnLBF2w581U2gf+Mat0j1stZE1E0
            MUjy8ydhcco4f6omXD8b6eowp1s/goXv0MdwltY5K2d8MWFVcutenw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-17T21:18:24Z"
    mac: ENC[AES256_GCM,data:fvmmj7J87Aw2rzaGlVhIw5/7QjSmfodPknRD+dvsXl7g16onGPh1rWVhLLiQBGpdddu+DzoNJdlHIY3jx0+2GDZwLuwz7eKWb5+WYeT4Nib69gjC0cLOgfh1LmJQys1v80v9ISgxCnUF6Hw/xnEnJgF3doSol082XRaUSyG2wwk=,iv:42Lap124Yk+/CjWy7qf4vFOaSqCWjz3wnN/A8HuMtgE=,tag:GJHP4NqHBrOLysoIAjiCZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
