immich:
  persistence:
    library:
      existingClaim: immich-library

controllers:
  main:
    containers:
      main:
        env:
          DB_HOSTNAME: "immich-db"
          DB_DATABASE_NAME: "immich"
          DB_USERNAME: "immich"
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-credentials
                key: db-password
          REDIS_HOSTNAME: "redis.redis.svc.lab.tanku.eu"
          REDIS_PORT: "6379"
          IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"

valkey:
  enabled: false

server:
  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host immich.lab.tanku.eu
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: immich-tls
          hosts:
            - *host
