clusterName: homelab
talosVersion: v1.13.6
kubernetesVersion: v1.33.2
endpoint: https://192.168.178.90:6443
domain: lab.tanku.eu

allowSchedulingOnControlPlanes: true

cniConfig:
  name: flannel

nodes:
  - hostname: metal0
    ipAddress: 192.168.178.90
    installDisk: /dev/nvme0n1
    machineSpec:
      mode: metal
    networkInterfaces:
      - interface: eno1
        dhcp: false
        addresses:
          - 192.168.178.90/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.178.1
    controlPlane: true
    patches:
      - |-
        machine:
          disks:
            - device: /dev/sdb
              partitions:
                - mountpoint: /var/mnt/media
