apiVersion: ENC[AES256_GCM,data:aoI=,iv:92xFWOB0ulvtPx7EtYB7LFq9Tkl1yJ8UEY8Htp2OEDI=,tag:/7VAS8U3Q3ndz1kKy+tciA==,type:str]
kind: ENC[AES256_GCM,data:rHAlVqdd,iv:nE9jMBf7ANxuRXhxCoadu45F2AxWoeE3ZfaMnLZQY7E=,tag:zpM9lfZhrmNXcSS4abPSqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NC2F0lvGPure8GaQGhg+tNcg+O0=,iv:/588ZJpAwBagVkJas9JMJ/Pi1Imv9ZzbdScZEG0UiOk=,tag:7dhN8wrvBRpCbeytiyAKUw==,type:str]
    namespace: ENC[AES256_GCM,data:jrIUdDbzhdQ=,iv:hxWJzUUQzI3kNKowOwWNpln0r8NpYmopCIS/qapHCgI=,tag:21HPDx/P5cbFuGLccheWSA==,type:str]
type: ENC[AES256_GCM,data:FRPcooTh,iv:BICIT8+xquGScG8oaFspPxHYVkWEivlC9f/HBeVmcQg=,tag:MZIrMWyW1mfx+d4a52MOHA==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WdWVpyN4X691N1zjDfCB8GsAgKSMoXEIJn33BGK2/v3+yTuGyjilA/7UQg==,iv:VA59VuayrpvYIus5Ll7yfXkouB52aA2udcEUYokcCF4=,tag:9KAb5NwwiPXxRfuVD4MA6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dlJ4SXl5dzIwU3kzbGsy
            MmRwamp4VmE0djBnUzk4S0p1ME9SMnZSa0RvCjZXaVhBdGRHQkt6cm9MTEpENmln
            b1g1SEliQ3ZTaHJ4NEVwOTZ6NnRpTjQKLS0tIDBjemgxN1FhbFVsTzdCT2lUQjND
            MjVKb0FUelNpSmcwZ2lscnRUTXIwczQK0NghFklHj42rQ4xbhg4cuShmPaJrfnTQ
            B3Bqb7Ds1dJJuVGG9ljj0XW7jEdtlfCFsrmnC9A8CRCWK4ETGQOhvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-17T13:15:03Z"
    mac: ENC[AES256_GCM,data:IfnkK1SrdCQV8l5TGkowlOzcOcVogqx/0Px4MLT/zNDV8jwcKxv4aD45HiwmvI82w9MntKuQMLffKd1Mv6WcTO2AmNU1gj56G+ZD8844Fo2agM2kVWn5dIWcuABQW9TKrYUukjDP4vP18vebQ+FJwAEqWcFjHMuzyLOubhHTPHA=,iv:NSZcyj6cQ29SxKPPwCiBDJcl1Pst7lg9QvvD0e2OhVc=,tag:kzSRDNjHDwI6wDESfWx6Dg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
