apiVersion: ENC[AES256_GCM,data:btw=,iv:mYm6YJOlrYuxQAklTtTDKqibxftWChQ1VAck2E67Z4E=,tag:4oLX3AAFUT4b//nBeqrQ+A==,type:str]
kind: ENC[AES256_GCM,data:wI9Uzg+q,iv:TeffuS+z4xyh/kgdQhVasE0pVM9FWUCn+9m7XZIIAVg=,tag:QqB7Ltyaro4FPImUq+jePw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3mmVFzRfgP8YZn93JbdDkw==,iv:mkDvdZKBwesU9SB21j5/3+ZxgtdPdxkaY9o9FYJnQNU=,tag:MzBkUzK1Wpcf+K8SOg4Wvg==,type:str]
    namespace: ENC[AES256_GCM,data:LNg0rNwR/Tpg6u9g,iv:dVV8Thy9qgiqr5o6absrqCV47qEZ0MxdAHdCt12+TGc=,tag:aBYoi3ASYRDrWkbckq3srA==,type:str]
type: ENC[AES256_GCM,data:OZyYeqtA,iv:NXLyrcqv2EEeWl03n5eCev9Zm7O42BJ6fJPatXVszvU=,tag:6DsXWGYklpCkEkr6QXEPvQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:kQCInQWkDQ5g,iv:v7+ekcShs19Xh4LTbH2oe/BJ0BHU6UiNf1TVUWD0frU=,tag:f83OfR1BoG/IC/R/+bmssg==,type:str]
    password: ENC[AES256_GCM,data:jdF4hPUclvvjzYVZsgDVm2KZ3GyFONU1MFDfhJ3DNDM=,iv:wKzeuYu23uvsBapNzW7aNMsNk0vlDot/c7WRHFNe3Yw=,tag:BRwNtdrpQB4msSP1GOZXxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT2EzYjRheC9PR0RRTys1
            Q1ZoRXE3NVlnNDdud3lZNWNyT01CSjNFeG5VCkZCUWJqRmkvamFnTmg1alFxNFNO
            R2hzVFIwQjZTV1pYdXNKZmUzZFpLOE0KLS0tIFE5T3hVcWVaaHVOUU81MzM2VWFs
            bDhLaHVpSjNnYjZtUzZKZThpZU82ajQKCIlhgrFqGCjn0sR5kYO2R+FXIOeIbcgM
            VvVtY/VfnqLTZrRckFXObVYopYI9O4vtIk6Fx12O5PMHvnviBY8u7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-14T16:30:59Z"
    mac: ENC[AES256_GCM,data:QGNAJhwQ4sMeiRqL02XcSI24l+7foSOZ86kV17ux0ZpUduE7KuvpCmuD0RUbRwDR3DnXYhL07AF6fdfsvQm3Ww/MNn5rNXtP5EK5bH1TSHWWA8UC4qnH1z1N5VxbySeKU3uAIg9T0kynr9KP/IgatiZay9USf2EyjJGp1+TvpBc=,iv:5AwgSuB1OrscH/PluqQrMXup0hrHpXkl1TU4TsAPJGk=,tag://kyxhcwklf70OgMHAZD2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
