apiVersion: ENC[AES256_GCM,data:0Fk=,iv:osnNcsTqN6x+aavq6XySqjAr441oQS7S2S9+IU0axsg=,tag:dBWN9FZGyMZiXAekPV6Mrw==,type:str]
kind: ENC[AES256_GCM,data:L2UeAHyK,iv:Qich46aRbqDisBiN/wa/0iGzdU2CCbSzVFRjsm4/ZII=,tag:Aj6vKvzol/H6e7/DfYRcgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mxbDNrzrjQlHoM/0OABbPEfV6HKz,iv:NsA3QL8IJfmiJkiTcH+RWX6XvDLFCgqkaUAWuJT4+8M=,tag:ZwDJ1D3d3KZPhADat75PLg==,type:str]
    namespace: ENC[AES256_GCM,data:m2px0ZBQpc5Q,iv:ZOFsRJEvxXPPbRPACofMiy2V8WB+3FvuqkgllyHUig4=,tag:Gcm5gVEETdqgvDMkCyRk+g==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:+jXv8Z0mW9iYRqbbqnmSrpY4ngZTkls0uXvm9GCYnsElSoD5xYBt4UakMnEiVpULBj0=,iv:ccWsX/Am457ebvjH1Vha0ZztX02bYKLr4EekitKJvkg=,tag:krqCKyuRuyz7P7y3ckPaqQ==,type:str]
    db-password: ENC[AES256_GCM,data:a0twaqAl/QfL2KBlIoiuXUu7uGxBOv/l0FqtjVGZX0Y=,iv:I1Aqns73E+91Vcqzhd8TdI0egj6wdiAIMfxGp65Qri0=,tag:AK2b/mWHYwZNS/EkkKQzow==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:NKIvHgc9FAhzbT00xWLlHpMPnZacvJBI,iv:/LhwOFfUbSoH7EPod8ED09QBNHOovKkFZuwNKiTOxxA=,tag:VZX+ff27fmSnTwDPN0TSJg==,type:str]
    bootstrap-token: ENC[AES256_GCM,data:rPm/nvGTZ8yqZf5Kye69EKCyNVmgJFyrr+Alaj9bQHGAQj8aQLxccA==,iv:6sHTS9kNkVKyrcGow/zz8vN4fv0V3333ikSGFpaUJvY=,tag:YX0Qvb7OxIjyU7U5RcL/Zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzN5T3RYVzlLOExFcXpT
            YW1vRldUdEVjZDd0VklzNytMaWpkc3N2VlR3Cjl4d3hOdkFCcjcwcm10Z1c0R0lC
            NkNOcWdBQnpuM3ZNalJXU3ZLNlE4OUkKLS0tIEFpWTVVSUxzSGtFa1h4UENTVDhz
            WjBxRi9udzg1RlR5YTdqRHFMb0ZOWk0KATMjzgMufljDQAurIwPV1edWEcT6Y37J
            FWa009PuV4nbnrlAvlyTcTVFCV1tkpxI7ZrZSHPUosL2SUhmN4SK9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cj453dwyx8q62qwe54svrdxpa07807jv7fkpftkd5ds0qmng5azqwnn2dj
    lastmodified: "2026-07-18T13:59:34Z"
    mac: ENC[AES256_GCM,data:W8nuU35tZQydlWrY650zAnqo9dMln2pm3FFc1NbYgjwGUpMOI5elcwHDxLbWOl6PKFDEs2liQ/5izsEte5vX3InimUh0djMuSOs2A3LeKyp0JbM+qkr8kT6lhXD9o2zGXNPBrwYKJHmrZDKVuDXs2XYpKvU3JEkjil/3VTbSVt0=,iv:20bSyeu0UYSNh67fCROLiaWpzmx1KKh1AoryWTf4fB8=,tag:g4WIc4H3DOGKY15bAe0/mA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
